name: Deploy Backend to EC2

on:
    push:
        paths:
            - "fashion-backend/**"
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Copy code to EC2 and restart container
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ec2-user
                port: ${{ secrets.EC2_PORT }}
                key: ${{ secrets.EC2_SSH_KEY }}
                source: "fashion-backend"
                target: "/home/ec2-user/backend"

            - name: SSH and deploy Docker container
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ec2-user
                port: ${{ secrets.EC2_PORT }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  cd /home/ec2-user/backend
                  docker stop backend || true
                  docker rm backend || true
                  docker build -t backend .
                  docker run -d -p 7000:7000 --name backend backend